export const TIMELINE_LABELS = {
  memories: {
    en: "Memories",
    fr: "Souvenirs",
    ar: "ذكريات",
    kab: "Tizemmarin",
    es: "Recuerdos",
    ru: "Воспоминания",
    zh: "记忆",
    hi: "यादें",
    ur: "یادیں",
    pt: "Memórias",
    tr: "Anılar",
    sw: "Kumbukumbu",
    de: "Erinnerungen",
    it: "Ricordi",
    ja: "思い出",
    bn: "স্মৃতি",
    fa: "خاطرات",
    zgh: "ⵜⵉⵣⴻⵎⵎⴰⵔⵉⵏ",
  },
  instant: {
    en: "Instant",
    fr: "Instant",
    ar: "لحظة",
    kab: "Azmez",
    es: "Instante",
    ru: "Момент",
    zh: "瞬间",
    hi: "पल",
    ur: "لمحہ",
    pt: "Instante",
    tr: "An",
    sw: "Wakati",
    de: "Moment",
    it: "Istante",
    ja: "瞬間",
    bn: "মুহূর্ত",
    fa: "لحظه",
    zgh: "ⴰⵣⵎⴻⵣ",
  },
  forever: {
    en: "Forever",
    fr: "Pour toujours",
    ar: "إلى الأبد",
    kab: "Akw",
    es: "Para siempre",
    ru: "Навсегда",
    zh: "永远",
    hi: "हमेशा के लिए",
    ur: "ہمیشہ کے لیے",
    pt: "Para sempre",
    tr: "Sonsuza",
    sw: "Milele",
    de: "Für immer",
    it: "Per sempre",
    ja: "永遠に",
    bn: "চিরকালের জন্য",
    fa: "برای همیشه",
    zgh: "Akw",
  },
} as const;

export type TimelineId = keyof typeof TIMELINE_LABELS;

export const getTimelineLabel = (timeline: TimelineId, lang: string): string => {
  const labels = TIMELINE_LABELS[timeline];
  return labels[lang as keyof typeof labels] || labels.en;
};
