export const UI_LABELS = {
  me: {
    en: "Me",
    fr: "Moi",
    ar: "أنا",
    kab: "Nekk",
    es: "Yo",
    ru: "Я",
    zh: "我",
    hi: "मैं",
    ur: "میں",
    pt: "Eu",
    tr: "Ben",
    sw: "Mimi",
    de: "Ich",
    it: "Io",
    ja: "私",
    bn: "আমি",
    fa: "من",
    zgh: "Nekk",
  },
  places: {
    en: "Places",
    fr: "Lieux",
    ar: "أماكن",
    kab: "Iɣeẓran",
    es: "Lugares",
    ru: "Места",
    zh: "地点",
    hi: "स्थान",
    ur: "مقامات",
    pt: "Lugares",
    tr: "Yerler",
    sw: "Maeneo",
    de: "Orte",
    it: "Luoghi",
    ja: "場所",
    bn: "স্থান",
    fa: "مکان‌ها",
    zgh: "Iɣeẓran",
  },
  circle: {
    en: "Circle",
    fr: "Cercle",
    ar: "دائرة",
    kab: "Aẓar",
    es: "Círculo",
    ru: "Круг",
    zh: "圈子",
    hi: "परिवार",
    ur: "حلقہ",
    pt: "Círculo",
    tr: "Çevre",
    sw: "Mzunguko",
    de: "Kreis",
    it: "Cerchio",
    ja: "サークル",
    bn: "পরিবার",
    fa: "دایره",
    zgh: "Aẓar",
  },
  whispers: {
    en: "Whispers",
    fr: "Murmures",
    ar: "همسات",
    kab: "Timessusin",
    es: "Susurros",
    ru: "Шёпот",
    zh: "低语",
    hi: "फुसफुसाहट",
    ur: "سرگوشیاں",
    pt: "Sussurros",
    tr: "Fısıltılar",
    sw: "Minong'ono",
    de: "Flüstern",
    it: "Sussurri",
    ja: "ささやき",
    bn: "ফিসফিস",
    fa: "نجواها",
    zgh: "Timessusin",
  },
  memories: {
    en: "Memories",
    fr: "Souvenirs",
    ar: "ذكريات",
    kab: "Tizemmarin",
    es: "Recuerdos",
    ru: "Воспоминания",
    zh: "记忆",
    hi: "यादें",
    ur: "یادیں",
    pt: "Memórias",
    tr: "Anılar",
    sw: "Kumbukumbu",
    de: "Erinnerungen",
    it: "Ricordi",
    ja: "思い出",
    bn: "স্মৃতি",
    fa: "خاطرات",
    zgh: "ⵜⵉⵣⴻⵎⵎⴰⵔⵉⵏ",
  },
  instant: {
    en: "Instant",
    fr: "Instant",
    ar: "لحظة",
    kab: "Azmez",
    es: "Instante",
    ru: "Момент",
    zh: "瞬间",
    hi: "पल",
    ur: "لمحہ",
    pt: "Instante",
    tr: "An",
    sw: "Wakati",
    de: "Moment",
    it: "Istante",
    ja: "瞬間",
    bn: "মুহূর্ত",
    fa: "لحظه",
    zgh: "ⴰⵣⵎⴻⵣ",
  },
  forever: {
    en: "Forever",
    fr: "Pour toujours",
    ar: "إلى الأبد",
    kab: "Akw",
    es: "Para siempre",
    ru: "Навсегда",
    zh: "永远",
    hi: "हमेशा के लिए",
    ur: "ہمیشہ کے لیے",
    pt: "Para sempre",
    tr: "Sonsuza",
    sw: "Milele",
    de: "Für immer",
    it: "Per sempre",
    ja: "永遠に",
    bn: "চিরকালের জন্য",
    fa: "برای همیشه",
    zgh: "Akw",
  },
  save: {
    en: "Save",
    fr: "Enregistrer",
    ar: "حفظ",
    kab: "Sekcem",
    es: "Guardar",
    ru: "Сохранить",
    zh: "保存",
    hi: "सहेजें",
    ur: "محفوظ کریں",
    pt: "Salvar",
    tr: "Kaydet",
    sw: "Hifadhi",
    de: "Speichern",
    it: "Salva",
    ja: "保存",
    bn: "সংরক্ষণ",
    fa: "ذخیره",
    zgh: "Sekcem",
  },
  cancel: {
    en: "Cancel",
    fr: "Annuler",
    ar: "إلغاء",
    kab: "Sefsed",
    es: "Cancelar",
    ru: "Отмена",
    zh: "取消",
    hi: "रद्द करें",
    ur: "منسوخ",
    pt: "Cancelar",
    tr: "İptal",
    sw: "Ghairi",
    de: "Abbrechen",
    it: "Annulla",
    ja: "キャンセル",
    bn: "বাতিল",
    fa: "لغو",
    zgh: "Sefsed",
  },
  logout: {
    en: "Log out",
    fr: "Se déconnecter",
    ar: "تسجيل الخروج",
    kab: "Ffeɣ",
    es: "Cerrar sesión",
    ru: "Выйти",
    zh: "退出",
    hi: "लॉग आउट",
    ur: "لاگ آؤٹ",
    pt: "Sair",
    tr: "Çıkış",
    sw: "Toka",
    de: "Abmelden",
    it: "Esci",
    ja: "ログアウト",
    bn: "লগ আউট",
    fa: "خروج",
    zgh: "Ffeɣ",
  },
  edit: {
    en: "Edit",
    fr: "Modifier",
    ar: "تعديل",
    kab: "Snefli",
    es: "Editar",
    ru: "Изменить",
    zh: "编辑",
    hi: "संपादित करें",
    ur: "ترمیم",
    pt: "Editar",
    tr: "Düzenle",
    sw: "Hariri",
    de: "Bearbeiten",
    it: "Modifica",
    ja: "編集",
    bn: "সম্পাদনা",
    fa: "ویرایش",
    zgh: "Snefli",
  },
  done: {
    en: "Done",
    fr: "Terminer",
    ar: "انتهى",
    kab: "Immed",
    es: "Listo",
    ru: "Готово",
    zh: "完成",
    hi: "हो गया",
    ur: "ہو گیا",
    pt: "Pronto",
    tr: "Tamam",
    sw: "Imemaliza",
    de: "Fertig",
    it: "Fatto",
    ja: "完了",
    bn: "সম্পন্ন",
    fa: "تمام",
    zgh: "Immed",
  },
  share: {
    en: "Share",
    fr: "Partager",
    ar: "مشاركة",
    kab: "Bḍu",
    es: "Compartir",
    ru: "Поделиться",
    zh: "分享",
    hi: "साझा करें",
    ur: "شیئر",
    pt: "Compartilhar",
    tr: "Paylaş",
    sw: "Shiriki",
    de: "Teilen",
    it: "Condividi",
    ja: "シェア",
    bn: "শেয়ার",
    fa: "اشتراک",
    zgh: "Bḍu",
  },
  delete: {
    en: "Delete",
    fr: "Supprimer",
    ar: "حذف",
    kab: "Kkes",
    es: "Eliminar",
    ru: "Удалить",
    zh: "删除",
    hi: "हटाएं",
    ur: "حذف کریں",
    pt: "Excluir",
    tr: "Sil",
    sw: "Futa",
    de: "Löschen",
    it: "Elimina",
    ja: "削除",
    bn: "মুছুন",
    fa: "حذف",
    zgh: "Kkes",
  },
  search: {
    en: "Search",
    fr: "Rechercher",
    ar: "بحث",
    kab: "Nadi",
    es: "Buscar",
    ru: "Поиск",
    zh: "搜索",
    hi: "खोजें",
    ur: "تلاش",
    pt: "Buscar",
    tr: "Ara",
    sw: "Tafuta",
    de: "Suchen",
    it: "Cerca",
    ja: "検索",
    bn: "অনুসন্ধান",
    fa: "جستجو",
    zgh: "Nadi",
  },
  settings: {
    en: "Settings",
    fr: "Paramètres",
    ar: "إعدادات",
    kab: "Iɣewwaren",
    es: "Ajustes",
    ru: "Настройки",
    zh: "设置",
    hi: "सेटिंग्स",
    ur: "ترتیبات",
    pt: "Configurações",
    tr: "Ayarlar",
    sw: "Mipangilio",
    de: "Einstellungen",
    it: "Impostazioni",
    ja: "設定",
    bn: "সেটিংস",
    fa: "تنظیمات",
    zgh: "Iɣewwaren",
  },
  members: {
    en: "Members",
    fr: "Membres",
    ar: "أعضاء",
    kab: "Iɛeggalen",
    es: "Miembros",
    ru: "Участники",
    zh: "成员",
    hi: "सदस्य",
    ur: "اراکین",
    pt: "Membros",
    tr: "Üyeler",
    sw: "Wanachama",
    de: "Mitglieder",
    it: "Membri",
    ja: "メンバー",
    bn: "সদস্য",
    fa: "اعضا",
    zgh: "Iɛeggalen",
  },
  invite: {
    en: "Invite",
    fr: "Inviter",
    ar: "دعوة",
    kab: "Nced",
    es: "Invitar",
    ru: "Пригласить",
    zh: "邀请",
    hi: "आमंत्रित करें",
    ur: "دعوت دیں",
    pt: "Convidar",
    tr: "Davet et",
    sw: "Alika",
    de: "Einladen",
    it: "Invita",
    ja: "招待",
    bn: "আমন্ত্রণ",
    fa: "دعوت",
    zgh: "Nced",
  },
  locate: {
    en: "Locate",
    fr: "Localiser",
    ar: "تحديد الموقع",
    kab: "Af-d",
    es: "Localizar",
    ru: "Найти",
    zh: "定位",
    hi: "स्थान खोजें",
    ur: "مقام تلاش کریں",
    pt: "Localizar",
    tr: "Konum bul",
    sw: "Tafuta mahali",
    de: "Orten",
    it: "Localizza",
    ja: "現在地",
    bn: "অবস্থান",
    fa: "موقعیت‌یابی",
    zgh: "Af-d",
  },
} as const;

export type UiLabelKey = keyof typeof UI_LABELS;

export const getLabel = (key: UiLabelKey, lang: string): string => {
  const labels = UI_LABELS[key];
  return labels[lang as keyof typeof labels] || labels.en;
};
