import type { Lang } from "@/lib/i18n";

/**
 * Extra UI copy keyed by English canonical string.
 * Used by pickLocalized when a call site only provides { fr, ar, en }.
 */
export type OverlayMap = Record<string, string>;

const es: OverlayMap = {
  "Voice only": "Solo voz",
  "Just your voice, no camera": "Solo tu voz, sin cámara",
  "Film myself": "Grabarme",
  "Your face, your story": "Tu cara, tu historia",
  "Memory Effect": "Efecto Recuerdo",
  "A photo or video behind you while you speak": "Una foto o vídeo detrás de ti mientras hablas",
  "A memory": "Un recuerdo",
  "A memory on Infeelit": "Un recuerdo en Infeelit",
  "A photo": "Una foto",
  "A video": "Un vídeo",
  "A video from my gallery": "Un vídeo de mi galería",
  "An unexpected error occurred.": "Ha ocurrido un error inesperado.",
  "Back to feed ✦": "Volver al feed ✦",
  "Begin your story here.": "Empieza aquí tu historia.",
  "Check your spam if you don't see it": "Revisa el spam si no lo ves",
  "Choose a background for your recording": "Elige un fondo para tu grabación",
  "Choose a custom image": "Elige una imagen personalizada",
  "Choose period": "Elige el periodo",
  "Choose preview": "Elige la vista previa",
  "Choose what you want to comment on.\\nYour face will appear in front.":
    "Elige sobre qué quieres comentar.\\nTu cara aparecerá delante.",
  "Continue with video": "Continuar con vídeo",
  "Continue →": "Continuar →",
  "Could not generate Echo Card.": "No se pudo generar la Echo Card.",
  "Could not save your name. Please try again.": "No se pudo guardar tu nombre. Inténtalo de nuevo.",
  "Could not send report.": "No se pudo enviar el reporte.",
  "Delivery date": "Fecha de entrega",
  "Discard recording": "Descartar grabación",
  "Enter Infeelit": "Entrar en Infeelit",
  "Error saving.": "Error al guardar.",
  Everyone: "Todos",
  "Ex: Family vacation 2024": "Ej: Vacaciones en familia 2024",
  "Ex: For you, on your wedding day": "Ej: Para ti, el día de tu boda",
  "Ex: In front of my childhood home": "Ej: Delante de la casa de mi infancia",
  "Finish ✓": "Terminar ✓",
  "First Name": "Nombre",
  Forever: "Para siempre",
  "Generating previews…": "Generando vistas previas…",
  "Give this moment a title.": "Ponle un título a este momento.",
  "House, school, toy, face...": "Casa, colegio, juguete, cara...",
  "Imported video": "Vídeo importado",
  "Infeelit may share a teaser without your name": "Infeelit puede compartir un avance sin tu nombre",
  Instant: "Instantáneo",
  "It will loop behind you": "Se repetirá detrás de ti",
  "Keep this memory ✦": "Conservar este recuerdo ✦",
  "Link copied!": "¡Enlace copiado!",
  "Listen before keeping...": "Escucha antes de guardar...",
  Me: "Yo",
  Memories: "Recuerdos",
  "Memory preserved": "Recuerdo conservado",
  "Message for the future": "Mensaje para el futuro",
  "Microphone not accessible.": "Micrófono no disponible.",
  "My memory": "Mi recuerdo",
  "Next question": "Siguiente pregunta",
  "Next question →": "Siguiente pregunta →",
  "No audio captured. Please try again.": "No se capturó audio. Inténtalo de nuevo.",
  "Plays in background while you speak": "Se reproduce de fondo mientras hablas",
  "Publish ✦": "Publicar ✦",
  REC: "REC",
  "Reason for report:": "Motivo del reporte:",
  "Record this moment →": "Grabar este momento →",
  "Recording is empty. Please try again.": "La grabación está vacía. Inténtalo de nuevo.",
  "Recording too large to keep locally.": "La grabación es demasiado grande para guardarla localmente.",
  Report: "Reportar",
  "Report sent. Thank you.": "Reporte enviado. Gracias.",
  Reported: "Reportado",
  "Saving...": "Guardando...",
  "Send to my family": "Enviar a mi familia",
  "Session expired. Please login again.": "Sesión caducada. Vuelve a iniciar sesión.",
  "Share it with your family": "Compártelo con tu familia",
  "Spontaneous memory": "Recuerdo espontáneo",
  "This voice deserves to stay.": "Esta voz merece quedarse.",
  "Try again": "Reintentar",
  "Upload failed.": "Error al subir.",
  "Video selected ✓": "Vídeo seleccionado ✓",
  "What smell instantly brings you back to your childhood home?":
    "¿Qué olor te lleva al instante a la casa de tu infancia?",
  "What's your name?": "¿Cómo te llamas?",
  "Where does this memory belong?": "¿Dónde encaja este recuerdo?",
  "Which image represents this memory?": "¿Qué imagen representa este recuerdo?",
  "You're signed in — keeping your memory…": "Has iniciado sesión — conservando tu recuerdo…",
  "You're signed in! Continue recording to publish your memory.":
    "¡Has iniciado sesión! Sigue grabando para publicar tu recuerdo.",
  "Your answer to:": "Tu respuesta a:",
  "Your circle will know you by this name.": "Tu círculo te conocerá por este nombre.",
  "a precious memory": "un recuerdo precioso",
  friend: "amigo/a",
  you: "tú",
  "← Back": "← Atrás",
  "⏹ Stop": "⏹ Parar",
  "✦ Allow anonymous teaser": "✦ Permitir avance anónimo",
  "🎬 Video background active": "🎬 Fondo de vídeo activo",
  "🖼️ Image background active": "🖼️ Fondo de imagen activo",
  Circles: "Círculos",
  Places: "Lugares",
  Whispers: "Susurros",
  Back: "Atrás",
  "Which part of your life?": "¿Qué parte de tu vida?",
  "Record a memory": "Grabar un recuerdo",
  "Import from my gallery": "Importar de mi galería",
  "Join free": "Únete gratis",
  "✦ Join free": "✦ Únete gratis",
  "✦ Rejoins gratuitement": "✦ Únete gratis",
  Childhood: "Infancia",
  Youth: "Juventud",
  Adulthood: "Adultez",
  "0-12 years": "0-12 años",
  "12-25 years": "12-25 años",
  "25-50 years": "25-50 años",
  "Before the world shaped you": "Antes de que el mundo te formara",
  "When everything was still possible": "Cuando todo aún era posible",
  "What you have built": "Lo que has construido",
  "Early Childhood": "Primera infancia",
  School: "Colegio",
  Pets: "Mascotas",
  "High School": "Instituto",
  "College Years": "Universidad",
  Friends: "Amigos",
  Travel: "Viajes",
  "Passions & Sport": "Pasiones y deporte",
  "Love & Marriage": "Amor y matrimonio",
  "Being a Parent": "Ser padre/madre",
  "Work & Career": "Trabajo y carrera",
  "Family Time": "Tiempo en familia",
  Challenges: "Pruebas",
};

const de: OverlayMap = {
  "Voice only": "Nur Stimme",
  "Just your voice, no camera": "Nur deine Stimme, ohne Kamera",
  "Film myself": "Mich filmen",
  "Your face, your story": "Dein Gesicht, deine Geschichte",
  "Memory Effect": "Erinnerungseffekt",
  "A photo or video behind you while you speak": "Ein Foto oder Video hinter dir, während du sprichst",
  "A memory": "Eine Erinnerung",
  "Continue →": "Weiter →",
  "← Back": "← Zurück",
  "⏹ Stop": "⏹ Stopp",
  Memories: "Erinnerungen",
  Instant: "Moment",
  Forever: "Für immer",
  Circles: "Kreise",
  Places: "Orte",
  Whispers: "Flüstern",
  Me: "Ich",
  Back: "Zurück",
  "Which part of your life?": "Welcher Teil deines Lebens?",
  "Next question": "Nächste Frage",
  "Publish ✦": "Veröffentlichen ✦",
  "Link copied!": "Link kopiert!",
  "Try again": "Erneut versuchen",
  "Saving...": "Speichern...",
  Childhood: "Kindheit",
  Youth: "Jugend",
  Adulthood: "Erwachsenenalter",
  "Early Childhood": "Frühe Kindheit",
  School: "Schule",
  Pets: "Haustiere",
  "High School": "Gymnasium",
  Friends: "Freunde",
  Travel: "Reisen",
};

const it: OverlayMap = {
  "Voice only": "Solo voce",
  "Just your voice, no camera": "Solo la tua voce, senza camera",
  "Film myself": "Filmarmi",
  "Your face, your story": "Il tuo volto, la tua storia",
  "Memory Effect": "Effetto Ricordo",
  "A photo or video behind you while you speak": "Una foto o un video dietro di te mentre parli",
  "A memory": "Un ricordo",
  "Continue →": "Continua →",
  "← Back": "← Indietro",
  "⏹ Stop": "⏹ Stop",
  Memories: "Ricordi",
  Instant: "Istante",
  Forever: "Per sempre",
  Circles: "Cerchi",
  Places: "Luoghi",
  Whispers: "Sussurri",
  Me: "Io",
  Back: "Indietro",
  "Which part of your life?": "Quale parte della tua vita?",
  "Next question": "Prossima domanda",
  "Publish ✦": "Pubblica ✦",
  Childhood: "Infanzia",
  Youth: "Giovinezza",
  Adulthood: "Età adulta",
};

const pt: OverlayMap = {
  "Voice only": "Só voz",
  "Just your voice, no camera": "Só a sua voz, sem câmara",
  "Film myself": "Filmar-me",
  "Your face, your story": "O seu rosto, a sua história",
  "Memory Effect": "Efeito Memória",
  "A photo or video behind you while you speak": "Uma foto ou vídeo atrás de si enquanto fala",
  "A memory": "Uma memória",
  "Continue →": "Continuar →",
  "← Back": "← Voltar",
  "⏹ Stop": "⏹ Parar",
  Memories: "Memórias",
  Instant: "Instantâneo",
  Forever: "Para sempre",
  Circles: "Círculos",
  Places: "Lugares",
  Whispers: "Sussurros",
  Me: "Eu",
  Back: "Voltar",
  "Which part of your life?": "Que parte da sua vida?",
  Childhood: "Infância",
  Youth: "Juventude",
  Adulthood: "Idade adulta",
};

const hi: OverlayMap = {
  "Voice only": "केवल आवाज़",
  "Film myself": "खुद को फिल्माएँ",
  "Memory Effect": "स्मृति प्रभाव",
  Circles: "वृत्त",
  Places: "स्थान",
  Whispers: "फुसफुसाहट",
  Me: "मैं",
  Back: "वापस",
  Childhood: "बचपन",
  Youth: "जवानी",
  Adulthood: "वयस्कता",
};

const ru: OverlayMap = {
  "Voice only": "Только голос",
  "Film myself": "Снять себя",
  "Memory Effect": "Эффект воспоминания",
  Circles: "Круги",
  Places: "Места",
  Whispers: "Шёпот",
  Me: "Я",
  Back: "Назад",
  Childhood: "Детство",
  Youth: "Юность",
  Adulthood: "Взрослость",
};

const zh: OverlayMap = {
  "Voice only": "仅声音",
  "Film myself": "拍摄自己",
  "Memory Effect": "回忆效果",
  Circles: "圈子",
  Places: "地点",
  Whispers: "低语",
  Me: "我",
  Back: "返回",
  Childhood: "童年",
  Youth: "青春",
  Adulthood: "成年",
};

const tr: OverlayMap = {
  "Voice only": "Sadece ses",
  "Film myself": "Kendimi çek",
  "Memory Effect": "Anı Efekti",
  Circles: "Çemberler",
  Places: "Yerler",
  Whispers: "Fısıltılar",
  Me: "Ben",
  Back: "Geri",
  Childhood: "Çocukluk",
  Youth: "Gençlik",
  Adulthood: "Yetişkinlik",
};

const sw: OverlayMap = {
  "Voice only": "Sauti tu",
  "Film myself": "Jirekodi",
  "Memory Effect": "Athari ya Kumbukumbu",
  Circles: "Duara",
  Places: "Mahali",
  Whispers: "Minong'ono",
  Me: "Mimi",
  Back: "Rudi",
};

const ur: OverlayMap = {
  "Voice only": "صرف آواز",
  "Film myself": "اپنا ریکارڈ",
  Circles: "حلقے",
  Places: "مقامات",
  Whispers: "سرگونشیاں",
  Me: "میں",
  Back: "واپس",
};

const ja: OverlayMap = {
  "Voice only": "音声のみ",
  "Film myself": "自分を撮る",
  "Memory Effect": "思い出エフェクト",
  Circles: "サークル",
  Places: "場所",
  Whispers: "ささやき",
  Me: "自分",
  Back: "戻る",
  Childhood: "子ども時代",
  Youth: "青春",
  Adulthood: "大人",
};

const bn: OverlayMap = {
  "Voice only": "শুধু কণ্ঠস্বর",
  "Film myself": "নিজেকে ধারণ",
  Circles: "বৃত্ত",
  Places: "স্থান",
  Whispers: "ফিসফিস",
  Me: "আমি",
  Back: "পিছনে",
};

const fa: OverlayMap = {
  "Voice only": "فقط صدا",
  "Film myself": "از خودم فیلم بگیرم",
  Circles: "حلقه‌ها",
  Places: "مکان‌ها",
  Whispers: "نجواها",
  Me: "من",
  Back: "بازگشت",
};

/** Kabyle-specific overrides; other strings fall back to French via pickLocalized */
const kab: OverlayMap = {
  "Voice only": "Avris kan",
  "Just your voice, no camera": "Avris-ik kan, war takamiṛat",
};

const zgh: OverlayMap = {
  "Voice only": "ⴰⵡⵔⵉⵙ ⴽⴰⵏ",
};

export const UI_STRING_OVERLAYS: Partial<Record<Lang, OverlayMap>> = {
  es,
  de,
  it,
  pt,
  hi,
  ru,
  zh,
  tr,
  sw,
  ur,
  ja,
  bn,
  fa,
  kab,
  zgh,
};
