# Spanish questions — abuela, familia, sobremesa, quinceañera, immigration, football, faith
ES = [
    ("childhood", "En brazos de abuela", "Cuéntanos sobre el recuerdo más fuerte que tienes en los brazos de tu abuela."),
    ("childhood", "El patio secreto", "¿Cuál era tu escondite favorito cuando eras niño o niña?"),
    ("childhood", "El primer día", "Cuéntanos cómo fue tu primer día de escuela — ¿quién te llevó de la mano?"),
    ("childhood", "El barrio", "¿Qué recuerdo del barrio te trae más calor — la tienda, el árbol, las voces?"),
    ("childhood", "Veranos de siesta", "¿Qué soñabas durante las siestas de verano bajo el ventilador?"),
    ("childhood", "Mi primera bicicleta", "¿Quién te regaló tu primera bicicleta y qué pasó ese día?"),
    ("childhood", "Lluvia de verano", "Cuéntanos tu recuerdo más divertido jugando bajo la lluvia."),
    ("childhood", "Cuentos de abuela", "¿Qué cuento de tu abuela sigue viviendo en tu corazón?"),
    ("childhood", "Casa llena", "¿Cuál fue el momento más bonito de vivir en una casa llena de familia?"),
    ("childhood", "La canción de mamá", "¿Qué canción o arrullo de tu madre todavía te da paz?"),
    ("childhood", "Fiestas de niño", "¿Qué papel tenías en las preparaciones de las fiestas cuando eras pequeño?"),
    ("childhood", "Con papá", "Cuéntanos sobre los paseos al mercado o a la escuela con tu padre."),
    ("childhood", "Día libre", "¿Qué hacías los días sin escuela — fútbol, televisión, juegos?"),
    ("childhood", "La vecina", "¿Qué te enseñó alguna vecina o tía del barrio que nunca olvidaste?"),
    ("childhood", "El regalo", "Cuéntanos sobre el regalo de tu infancia que te dejó sin palabras."),
    ("childhood", "Vacaciones", "¿Qué recuerdas de las vacaciones en casa de los abuelos o en el pueblo?"),
    ("childhood", "Juegos de patio", "¿Cuál era tu juego favorito y con quién lo jugabas?"),
    ("childhood", "Mi primer dinero", "Cuéntanos la primera vez que ganaste tu propio dinero."),
    ("childhood", "Un miedo", "¿Qué miedo de la infancia recuerdas y quién te ayudó a superarlo?"),
    ("childhood", "El balón", "Cuéntanos sobre tu primer balón de fútbol o tu equipo favorito de niño."),
    ("family", "La lección de papá", "¿Qué lección de vida más importante te enseñó tu padre?"),
    ("family", "La cocina de mamá", "¿Qué plato de tu madre sigue siendo el mejor del mundo para ti?"),
    ("family", "Hermanos", "Cuéntanos tu recuerdo más bonito o más divertido con tus hermanos."),
    ("family", "Un tío querido", "¿Qué consejo de un tío o tía sigue guiándote hoy?"),
    ("family", "La mesa familiar", "Cuéntanos sobre una noche memorable alrededor de la mesa familiar."),
    ("family", "La voz del abuelo", "¿Cómo hablaba tu abuelo — qué frase suya todavía escuchas?"),
    ("family", "Una boda", "¿Qué recuerdo de una boda o celebración familiar guardas en el corazón?"),
    ("family", "Juntos en la enfermedad", "Cuéntanos cómo la familia se unió cuando alguien estuvo enfermo."),
    ("family", "La foto antigua", "¿Qué historia te cuenta la foto familiar más antigua que tienes?"),
    ("family", "Casa de abuela", "¿Qué hacía especial la casa de tu abuela — qué olía, qué sonaba?"),
    ("family", "Cómo nos conocimos", "Cuéntanos la historia de cómo conociste a tu pareja."),
    ("family", "La risa de mis hijos", "¿Qué momento con tus hijos te tocó el alma?"),
    ("family", "Una reconciliación", "Cuéntanos sobre un desacuerdo familiar que terminó fortaleciendo el amor."),
    ("family", "La cocina de abuela", "¿Qué aroma de la cocina de tu abuela todavía te transporta?"),
    ("family", "Familia numerosa", "¿Qué aprendiste de vivir en una familia grande y ruidosa?"),
    ("family", "La canción de casa", "¿Qué canción o oración sonaba en tu casa cada mañana o cada noche?"),
    ("family", "La bendición", "Cuéntanos sobre una bendición o abrazo de un mayor que nunca olvidaste."),
    ("family", "Un viaje juntos", "¿Qué recuerdas de un viaje en familia — adónde fueron y qué pasó?"),
    ("family", "El pariente querido", "¿Quién era ese pariente que siempre te hacía sentir en casa?"),
    ("family", "Nuestra fuerza", "¿En qué momento sentiste que tu familia era invencible?"),
    ("lessons", "La lección de la vida", "¿Cuál fue la lección más difícil pero más necesaria que te dio la vida?"),
    ("lessons", "Las palabras de papá", "¿Qué dijo tu padre que no entendiste entonces pero sí ahora?"),
    ("lessons", "Del fracaso", "Cuéntanos sobre un fracaso que te enseñó a levantarte."),
    ("lessons", "La honestidad", "¿Qué te enseñaron en casa sobre decir la verdad?"),
    ("lessons", "El fruto del esfuerzo", "¿Cuándo sentiste por primera vez que el trabajo duro valía la pena?"),
    ("lessons", "La paciencia", "¿De quién aprendiste a tener paciencia?"),
    ("lessons", "El valor de estudiar", "¿Quién te inspiró a estudiar y cómo lo hizo?"),
    ("lessons", "De un error", "¿Qué error nunca repetiste y qué aprendiste de él?"),
    ("lessons", "Ayudar a otros", "¿Qué te enseñó ayudar a alguien que lo necesitaba?"),
    ("lessons", "El tiempo", "¿Cuándo entendiste lo valioso que es el tiempo?"),
    ("lessons", "La humildad", "¿De dónde aprendiste a ser humilde?"),
    ("lessons", "Familia primero", "¿Qué experiencia te enseñó que la familia va primero?"),
    ("lessons", "Confiar en mí", "¿Cuándo y cómo aprendiste a confiar en ti mismo?"),
    ("lessons", "Perdonar", "Cuéntanos sobre un momento en que aprendiste a perdonar."),
    ("lessons", "Decir la verdad", "¿Quién te dio el valor de decir la verdad?"),
    ("traditions", "La Nochebuena", "Cuéntanos tu recuerdo más querido de Nochebuena o Navidad en familia."),
    ("traditions", "La sobremesa", "¿Qué conversaciones quedan en tu memoria después de la sobremesa dominical?"),
    ("traditions", "La comida del domingo", "¿Qué plato del domingo solo sabe igual en casa de mamá o abuela?"),
    ("traditions", "La misa o la fe", "¿Qué tradición de fe o de oración sigue viva en tu familia?"),
    ("traditions", "La quinceañera", "Cuéntanos sobre una quinceañera, bautizo o celebración que marcó tu familia."),
    ("traditions", "La boda tradicional", "¿Qué rito de boda te parece más hermoso y por qué?"),
    ("traditions", "El Día de los Muertos", "¿Cómo honra tu familia a quienes ya no están?"),
    ("traditions", "El cumpleaños", "¿Qué tradición de cumpleaños se repite en tu familia generación tras generación?"),
    ("traditions", "La Semana Santa", "Cuéntanos sobre una tradición de Semana Santa o Pascua en tu hogar."),
    ("traditions", "El Año Nuevo", "¿Cómo recibe tu familia el Año Nuevo — qué rituales tienen?"),
    ("traditions", "La receta secreta", "¿Qué receta familiar solo se hace en ocasiones especiales?"),
    ("traditions", "Las posadas", "Cuéntanos sobre posadas, villancicos u otra tradición navideña de tu infancia."),
    ("traditions", "El refrán de abuela", "¿Qué dicho o refrán de tu abuela repites hasta hoy?"),
    ("traditions", "La fiesta del pueblo", "¿Qué fiesta del pueblo o del barrio guardas en el corazón?"),
    ("traditions", "Lo que quiero pasar", "¿Qué tradición de tu familia quieres que siga viva?"),
    ("migration", "La decisión", "Cuéntanos cómo se tomó la decisión de emigrar — quién lo propuso y qué sintieron."),
    ("migration", "El primer día lejos", "¿Cómo fue tu primer día en el país nuevo — qué extrañaste primero?"),
    ("migration", "Extrañar el hogar", "¿Qué recuerdo de casa te golpea más fuerte cuando estás lejos?"),
    ("migration", "Enviar dinero", "Cuéntanos sobre enviar dinero a la familia — por qué, cómo, qué sentiste."),
    ("migration", "El idioma", "¿Cómo fue aprender un idioma nuevo — qué fue lo más difícil?"),
    ("migration", "Navidad lejos", "¿Cómo celebraste una fiesta importante lejos de casa?"),
    ("migration", "El regreso", "Cuéntanos sobre la primera vez que volviste a casa — quién te esperó en el aeropuerto."),
    ("migration", "Por los hijos", "¿Qué historia hay detrás de mudarse por la educación de tus hijos?"),
    ("migration", "Buscar trabajo", "Cuéntanos sobre la lucha de encontrar trabajo en un lugar nuevo."),
    ("migration", "Dos hogares", "¿Cómo se siente tener el corazón dividido entre dos países?"),
    ("migration", "Los papeles", "¿Qué recuerdo tienes del proceso de visa o documentos?"),
    ("migration", "Sabor de casa", "¿Cuándo extrañaste más la comida de tu madre o abuela?"),
    ("migration", "La distancia", "Cuéntanos sobre el día o la noche más difícil lejos de la familia."),
    ("migration", "Hacerse lugar", "¿Cómo construiste tu identidad en un lugar nuevo?"),
    ("migration", "El sueño de volver", "¿Sueñas con regresar — qué te lo impide o qué te lo permite?"),
    ("legacy", "Lo que quiero dejar", "¿Qué quieres dejar a tus hijos o nietos más allá del dinero?"),
    ("legacy", "El apellido", "¿Hay una historia detrás de tu apellido que quieras contar?"),
    ("legacy", "Nuestra historia", "Cuéntanos la historia de dónde viene tu familia y cómo llegó aquí."),
    ("legacy", "Una lección para siempre", "¿Qué quieres que la próxima generación nunca olvide?"),
    ("legacy", "Cómo recordarme", "¿Cómo quieres que te recuerden?"),
    ("legacy", "La foto que cuenta", "¿Qué historia esconde una foto antigua que debes contar?"),
    ("legacy", "Lo de abuela", "¿Qué objeto o enseñanza de tu abuela quieres pasar adelante?"),
    ("legacy", "El pueblo", "Cuéntanos sobre el pueblo o la casa donde creció tu familia."),
    ("legacy", "Mantener unidos", "¿Qué consejo das para mantener unida a la familia?"),
    ("legacy", "Mi lucha", "¿Qué parte de tu lucha quieres que conozcan tus hijos?"),
    ("legacy", "El momento feliz", "¿Cuál es el momento de tu vida que quieres que viva para siempre?"),
    ("legacy", "Perdón o gracias", "¿A quién quieres pedir perdón o dar las gracias — y por qué?"),
    ("legacy", "Un sueño pendiente", "¿Hay un sueño tuyo que quieres que la próxima generación cumpla?"),
    ("legacy", "La tradición viva", "¿Qué tradición es la más importante de mantener viva?"),
    ("legacy", "Mi mensaje final", "¿Qué mensaje quieres dejar a quienes más amas?"),
]
