# Portuguese questions — vovó, saudade, carnaval, futebol, immigration, faith
PT = [
    ("childhood", "No colo da vovó", "Conte-nos sobre a memória mais forte que você tem no colo da sua avó."),
    ("childhood", "O esconderijo", "Qual era o seu esconderijo secreto favorito quando criança?"),
    ("childhood", "O primeiro dia", "Como foi seu primeiro dia de escola — quem segurou sua mão?"),
    ("childhood", "O bairro", "Qual memória do bairro traz mais calor — a padaria, a árvore, as vozes?"),
    ("childhood", "Sesta de verão", "O que você sonhava durante as sestas de verão debaixo do ventilador?"),
    ("childhood", "Minha primeira bike", "Quem te deu sua primeira bicicleta e o que aconteceu naquele dia?"),
    ("childhood", "Chuva de verão", "Conte-nos sua memória mais divertida brincando na chuva."),
    ("childhood", "Histórias da vovó", "Qual história da sua avó ainda vive no seu coração?"),
    ("childhood", "Casa cheia", "Qual foi o momento mais bonito de viver numa casa cheia de família?"),
    ("childhood", "A canção da mãe", "Qual canção ou cantiga de ninar da sua mãe ainda te acalma?"),
    ("childhood", "Festas de criança", "Qual era o seu papel nas preparações das festas quando pequeno?"),
    ("childhood", "Com o pai", "Conte-nos sobre os passeios ao mercado ou à escola com seu pai."),
    ("childhood", "Dia livre", "O que você fazia nos dias sem escola — futebol, televisão, brincadeiras?"),
    ("childhood", "A vizinha", "O que alguma vizinha ou tia do bairro te ensinou que nunca esqueceu?"),
    ("childhood", "O presente", "Conte-nos sobre o presente da infância que te deixou sem palavras."),
    ("childhood", "Férias", "O que você lembra das férias na casa dos avós ou no interior?"),
    ("childhood", "Brincadeiras de rua", "Qual era seu jogo favorito e com quem você brincava?"),
    ("childhood", "Meu primeiro dinheiro", "Conte-nos sobre a primeira vez que você ganhou seu próprio dinheiro."),
    ("childhood", "Um medo", "Que medo da infância você lembra e quem te ajudou a superá-lo?"),
    ("childhood", "A bola", "Conte-nos sobre sua primeira bola de futebol ou time favorito de criança."),
    ("family", "A lição do pai", "Qual foi a lição de vida mais importante que seu pai te ensinou?"),
    ("family", "A cozinha da mãe", "Qual prato da sua mãe ainda é o melhor do mundo para você?"),
    ("family", "Irmãos", "Conte-nos sua memória mais bonita ou mais engraçada com seus irmãos."),
    ("family", "Um tio querido", "Que conselho de um tio ou tia ainda te guia hoje?"),
    ("family", "A mesa da família", "Conte-nos sobre uma noite memorável ao redor da mesa da família."),
    ("family", "A voz do avô", "Como seu avô falava — que frase dele você ainda escuta?"),
    ("family", "Um casamento", "Que memória de um casamento ou celebração familiar você guarda no coração?"),
    ("family", "Juntos na doença", "Conte-nos como a família se uniu quando alguém ficou doente."),
    ("family", "A foto antiga", "Que história a foto de família mais antiga te conta?"),
    ("family", "Casa da vovó", "O que fazia especial a casa da sua avó — cheiros, sons, atmosfera?"),
    ("family", "Como nos conhecemos", "Conte-nos a história de como você conheceu seu parceiro ou parceira."),
    ("family", "O riso dos filhos", "Que momento com seus filhos tocou sua alma?"),
    ("family", "Uma reconciliação", "Conte-nos sobre um desentendimento familiar que fortaleceu o amor."),
    ("family", "A cozinha da vovó", "Que aroma da cozinha da sua avó ainda te transporta?"),
    ("family", "Família grande", "O que você aprendeu vivendo numa família grande e barulhenta?"),
    ("family", "A canção de casa", "Que canção ou oração soava em sua casa toda manhã ou toda noite?"),
    ("family", "A bênção", "Conte-nos sobre uma bênção ou abraço de um mais velho que nunca esqueceu."),
    ("family", "Uma viagem juntos", "O que você lembra de uma viagem em família — para onde foram e o que aconteceu?"),
    ("family", "O parente querido", "Quem era aquele parente que sempre te fazia sentir em casa?"),
    ("family", "Nossa força", "Em que momento você sentiu que sua família era invencível?"),
    ("lessons", "A lição da vida", "Qual foi a lição mais difícil mas mais necessária que a vida te deu?"),
    ("lessons", "As palavras do pai", "O que seu pai disse que você não entendeu então mas entende agora?"),
    ("lessons", "Do fracasso", "Conte-nos sobre um fracasso que te ensinou a se levantar."),
    ("lessons", "A honestidade", "O que te ensinaram em casa sobre dizer a verdade?"),
    ("lessons", "O fruto do esforço", "Quando você sentiu pela primeira vez que o trabalho duro valia a pena?"),
    ("lessons", "A paciência", "De quem você aprendeu a ter paciência?"),
    ("lessons", "O valor de estudar", "Quem te inspirou a estudar e como fez isso?"),
    ("lessons", "De um erro", "Que erro você nunca repetiu e o que aprendeu com ele?"),
    ("lessons", "Ajudar outros", "O que te ensinou ajudar alguém que precisava?"),
    ("lessons", "O tempo", "Quando você entendeu o quanto o tempo é valioso?"),
    ("lessons", "A humildade", "De onde você aprendeu a ser humilde?"),
    ("lessons", "Família primeiro", "Que experiência te ensinou que a família vem em primeiro lugar?"),
    ("lessons", "Confiar em mim", "Quando e como você aprendeu a confiar em si mesmo?"),
    ("lessons", "Perdoar", "Conte-nos sobre um momento em que você aprendeu a perdoar."),
    ("lessons", "Dizer a verdade", "Quem te deu coragem de dizer a verdade?"),
    ("traditions", "O Natal em família", "Conte-nos sua memória mais querida de Natal ou festa de fim de ano em família."),
    ("traditions", "O almoço de domingo", "Que prato de domingo só tem o mesmo gosto na casa da mãe ou da vovó?"),
    ("traditions", "A fé em casa", "Que tradição de fé ou oração ainda vive na sua família?"),
    ("traditions", "O carnaval", "Conte-nos sobre o carnaval, festa junina ou outra celebração da sua infância."),
    ("traditions", "O batizado", "Conte-nos sobre um batizado, festa de quinze anos ou celebração que marcou sua família."),
    ("traditions", "O casamento tradicional", "Que rito de casamento você acha mais bonito e por quê?"),
    ("traditions", "Finados", "Como sua família homenageia quem já partiu?"),
    ("traditions", "O aniversário", "Que tradição de aniversário se repete na sua família geração após geração?"),
    ("traditions", "A Páscoa", "Conte-nos sobre uma tradição de Páscoa ou Semana Santa no seu lar."),
    ("traditions", "O Ano Novo", "Como sua família recebe o Ano Novo — que rituais vocês têm?"),
    ("traditions", "A receita secreta", "Que receita de família só é feita em ocasiões especiais?"),
    ("traditions", "O ditado da vovó", "Que ditado ou provérbio da sua avó você repete até hoje?"),
    ("traditions", "A festa do interior", "Que festa do interior ou do bairro você guarda no coração?"),
    ("traditions", "O café da tarde", "Como era o café da tarde ou chá em família — quem servia, do que se falava?"),
    ("traditions", "O que quero passar", "Que tradição da sua família você quer que continue viva?"),
    ("migration", "A decisão", "Conte-nos como foi tomada a decisão de emigrar — quem propôs e o que sentiram."),
    ("migration", "O primeiro dia longe", "Como foi seu primeiro dia no país novo — o que você sentiu falta primeiro?"),
    ("migration", "A saudade", "Que memória de casa te atinge mais forte quando você está longe?"),
    ("migration", "Enviar dinheiro", "Conte-nos sobre enviar dinheiro para a família — por quê, como, o que sentiu."),
    ("migration", "O idioma", "Como foi aprender um idioma novo — o que foi mais difícil?"),
    ("migration", "Natal longe", "Como você celebrou uma festa importante longe de casa?"),
    ("migration", "O retorno", "Conte-nos sobre a primeira vez que voltou para casa — quem te esperou no aeroporto."),
    ("migration", "Pelos filhos", "Que história há por trás de se mudar pela educação dos filhos?"),
    ("migration", "Buscar trabalho", "Conte-nos sobre a luta de encontrar trabalho num lugar novo."),
    ("migration", "Dois lares", "Como é ter o coração dividido entre dois países?"),
    ("migration", "Os documentos", "Que memória você tem do processo de visto ou documentos?"),
    ("migration", "Sabor de casa", "Quando você mais sentiu falta da comida da sua mãe ou avó?"),
    ("migration", "A distância", "Conte-nos sobre o dia ou a noite mais difícil longe da família."),
    ("migration", "Fazer seu lugar", "Como você construiu sua identidade num lugar novo?"),
    ("migration", "O sonho de voltar", "Você sonha em voltar — o que impede ou permite?"),
    ("legacy", "O que quero deixar", "O que você quer deixar para seus filhos ou netos além do dinheiro?"),
    ("legacy", "O sobrenome", "Há uma história por trás do seu sobrenome que você quer contar?"),
    ("legacy", "Nossa história", "Conte-nos a história de onde sua família veio e como chegou aqui."),
    ("legacy", "Uma lição para sempre", "O que você quer que a próxima geração nunca esqueça?"),
    ("legacy", "Como me lembrar", "Como você quer ser lembrado?"),
    ("legacy", "A foto que conta", "Que história esconde uma foto antiga que você deve contar?"),
    ("legacy", "O legado da vovó", "Que objeto ou ensinamento da sua avó você quer passar adiante?"),
    ("legacy", "O interior", "Conte-nos sobre o interior ou a casa onde sua família cresceu."),
    ("legacy", "Manter unidos", "Que conselho você dá para manter a família unida?"),
    ("legacy", "Minha luta", "Que parte da sua luta você quer que seus filhos conheçam?"),
    ("legacy", "O momento feliz", "Qual é o momento da sua vida que você quer que viva para sempre?"),
    ("legacy", "Perdão ou gratidão", "A quem você quer pedir perdão ou agradecer — e por quê?"),
    ("legacy", "Um sonho pendente", "Há um sonho seu que você quer que a próxima geração realize?"),
    ("legacy", "A tradição viva", "Que tradição é a mais importante de manter viva?"),
    ("legacy", "Minha mensagem final", "Que mensagem você quer deixar para quem mais ama?"),
]
