# Swahili questions — bibi/babu, ubuntu, chai, extended family, village, oral tradition
SW = [
    ("childhood", "Mikononi mwa bibi", "Tuambie kuhusu kumbukumbu yenye nguvu zaidi ulipokuwa mikononi mwa bibi au babu yako."),
    ("childhood", "Mahali pa siri", "Ulikuwa na mahali gani pa kujificha ukiwa mtoto?"),
    ("childhood", "Siku ya kwanza", "Siku yako ya kwanza shuleni ilikuwaje — nani alikushika mkono?"),
    ("childhood", "Kijiji chetu", "Kumbukumbu gani ya kijiji au mtaa inakuletea joto zaidi?"),
    ("childhood", "Usingizi wa mchana", "Ulikuwa unaota nini wakati wa kulala mchana chini ya upepo?"),
    ("childhood", "Baiskeli ya kwanza", "Nani alikupa baiskeli yako ya kwanza na nini kilitokea siku hiyo?"),
    ("childhood", "Mvua ya furaha", "Tuambie kumbukumbu yako ya kucheza mvua ukiwa mtoto."),
    ("childhood", "Hadithi za bibi", "Hadithi gani ya bibi bado inaishi moyoni mwako?"),
    ("childhood", "Familia kubwa", "Ni wakati gani ulio na furaha zaidi ukiishi na familia kubwa?"),
    ("childhood", "Wimbo wa mama", "Wimbo au nyimbo gani ya mama bado inakutuliza?"),
    ("childhood", "Maandalizi ya sherehe", "Ulikuwa na jukumu gani katika maandalizi ya sherehe ukiwa mtoto?"),
    ("childhood", "Na baba", "Tuambie kuhusu safari za kwenda shule au sokoni na baba yako."),
    ("childhood", "Siku ya mapumziko", "Ulifanya nini siku za mapumziko — michezo, televisheni, au nyingine?"),
    ("childhood", "Jirani yetu", "Jirani au shangazi alikufundisha nini ambacho hukusahau?"),
    ("childhood", "Zawadi ya kwanza", "Tuambie kuhusu zawadi ya utotoni iliyokushangaza — nani alikupa?"),
    ("childhood", "Likizo za msimu", "Unakumbuka likizo za kijijini au nyumbani kwa babu na bibi?"),
    ("childhood", "Michezo ya nje", "Mchezo gani uliupenda zaidi na nani ulicheza naye?"),
    ("childhood", "Pesa yangu ya kwanza", "Tuambie mara ya kwanza ulipopata pesa zako mwenyewe."),
    ("childhood", "Hofu ya utotoni", "Unakumbuka hofu gani ya utotoni na nani alikusaidia kuishinda?"),
    ("childhood", "Chai asubuhi", "Unakumbuka jinsi chai ya asubuhi ilivyokuwa nyumbani — nani aliiandaa?"),
    ("family", "Somo la baba", "Baba yako alikufundisha somo gani muhimu zaidi la maisha?"),
    ("family", "Jikoni kwa mama", "Chakula gani cha mama bado ni bora zaidi ulimwenguni kwako?"),
    ("family", "Ndugu zangu", "Tuambie kumbukumbu yako ya kupendeza au ya kuchekesha na ndugu zako."),
    ("family", "Mjomba au shangazi", "Ushauri gani kutoka kwa mjomba au shangazi bado unakuongoza leo?"),
    ("family", "Meza ya familia", "Tuambie kuhusu jioni moja ya kukumbukwa mezani mwa familia."),
    ("family", "Sauti ya babu", "Babu yako alizungumzaje — ni maneno gani bado unayasikia?"),
    ("family", "Harusi ya familia", "Kumbukumbu gani ya harusi au sherehe ya familia unaihifadhi moyoni?"),
    ("family", "Pamoja katika ugonjwa", "Tuambie jinsi familia ilivyoungana mtu alipokuwa mgonjwa."),
    ("family", "Picha ya zamani", "Picha ya familia ya zamani inasimulia hadithi gani?"),
    ("family", "Nyumba ya bibi", "Nini kilifanya nyumba ya bibi kuwa maalum — harufu, sauti, hali?"),
    ("family", "Jinsi tulivyokutana", "Tuambie hadithi ya jinsi ulivyokutana na mpenzi wako."),
    ("family", "Kicheko cha watoto", "Ni wakati gani na watoto wako uliogusa moyo wako?"),
    ("family", "Upatanisho", "Tuambie kuhusu mgogoro wa familia uliokomesha na kuimarisha upendo."),
    ("family", "Jikoni kwa bibi", "Harufu gani kutoka jikoni ya bibi bado inakurudisha nyuma?"),
    ("family", "Familia kubwa", "Ulijifunza nini kwa kuishi katika familia kubwa na yenye kelele?"),
    ("family", "Wimbo wa nyumbani", "Wimbo au sala gani ilisikika nyumbani kila asubuhi au jioni?"),
    ("family", "Baraka ya wazee", "Tuambie kuhusu baraka au kukumbatia kwa mzee ambayo hukusahau kamwe."),
    ("family", "Safari ya familia", "Unakumbuka safari gani ya familia — mlikwenda wapi na nini kilitokea?"),
    ("family", "Jamaa mpendwa", "Ni jamaa gani ambaye kila mara alikufanya uhisi uko nyumbani?"),
    ("family", "Nguvu yetu", "Ni wakati gani uligundua familia yako haishindiki?"),
    ("lessons", "Somo la maisha", "Maisha yalikufundisha somo gani gumu lakini muhimu zaidi?"),
    ("lessons", "Maneno ya baba", "Baba yako alisema nini ambacho hukuelewa wakati huo lakini sasa unaelewa?"),
    ("lessons", "Kutoka kushindwa", "Tuambie kuhusu kushindwa kulichokufundisha kuinuka tena."),
    ("lessons", "Uaminifu", "Nyumbani ulifundishwa nini kuhusu kusema ukweli?"),
    ("lessons", "Matunda ya juhudi", "Ulipata lini mara ya kwanza kuhisi kuwa kazi ngumu inastahili?"),
    ("lessons", "Uvumilivu", "Ulifundishwa uvumilivu na nani?"),
    ("lessons", "Thamani ya elimu", "Nani alikuchochea kusoma na alifanyaje?"),
    ("lessons", "Kutoka kosa", "Kosa gani hukurudia tena na ulijifunza nini kutoka kwalo?"),
    ("lessons", "Kusaidia wengine", "Kusaidia mtu aliyehitaji kukufundisha nini?"),
    ("lessons", "Muda", "Ulipata lini kuelewa thamani ya muda?"),
    ("lessons", "Unyenyekevu", "Ulifundishwa unyenyekevu wapi?"),
    ("lessons", "Familia kwanza", "Uzoefu gani ulikufundisha kuweka familia mbele?"),
    ("lessons", "Kujiamini", "Ulipata lini na vipi kujiamini?"),
    ("lessons", "Kusamehe", "Tuambie kuhusu wakati ulipojifunza kusamehe."),
    ("lessons", "Kusema ukweli", "Nani alikupa ujasiri wa kusema ukweli?"),
    ("traditions", "Siku ya Krismasi", "Tuambie kumbukumbu yako ya kupendeza zaidi ya Krismasi au sherehe ya mwisho wa mwaka."),
    ("traditions", "Chakula cha Jumapili", "Chakula gani cha Jumapili kinanuka tu nyumbani kwa mama au bibi?"),
    ("traditions", "Imani nyumbani", "Ni desturi gani ya imani au sala bado inaendelea katika familia yako?"),
    ("traditions", "Harusi ya jadi", "Ni ibada gani ya harusi unayoona ni nzuri zaidi na kwa nini?"),
    ("traditions", "Kumbukumbu ya waliotuacha", "Familia yako inawakumbuka vipi waliotuacha?"),
    ("traditions", "Siku ya kuzaliwa", "Ni desturi gani ya siku ya kuzaliwa inarudiwa kizazi hadi kizazi?"),
    ("traditions", "Eid au Idd", "Tuambie kuhusu Eid, Idd au sherehe nyingine ya familia yako."),
    ("traditions", "Mwaka mpya", "Familia yako inakaribisha mwaka mpya vipi — ni desturi gani?"),
    ("traditions", "Mapishi ya siri", "Ni mapishi gani ya familia yanayotayarishwa tu katika sherehe maalum?"),
    ("traditions", "Methali ya bibi", "Ni methali gani ya bibi bado unairudia leo?"),
    ("traditions", "Tamasha la kijiji", "Ni tamasha gani la kijiji au mtaa unaihifadhi moyoni?"),
    ("traditions", "Hadithi za mdomo", "Tuambie kuhusu hadithi za mdomo au utamaduni wa kusimulia katika familia yako."),
    ("traditions", "Chai ya jioni", "Chai ya jioni ilikuwaje — nani aliiandaa na mnazungumza nini?"),
    ("traditions", "Ubuntu nyumbani", "Tuambie jinsi ubuntu — kuwa na wengine — ulivyofunikwa katika desturi za familia yako."),
    ("traditions", "Ninachotaka kuendeleza", "Ni desturi gani ya familia yako unayotaka iendelee?"),
    ("migration", "Uamuzi wa kuhamia", "Tuambie jinsi uamuzi wa kuhamia ulivyochukuliwa — nani alipendekeza na mlihisi nini?"),
    ("migration", "Siku ya kwanza mbali", "Siku yako ya kwanza nchi au mji mpya ilikuwaje — ulichokosa nini kwanza?"),
    ("migration", "Kumkosa nyumbani", "Kumbukumbu gani ya nyumbani inakupiga nguvu zaidi ukiwa mbali?"),
    ("migration", "Kutuma pesa", "Tuambie kuhusu kutuma pesa kwa familia — kwa nini, vipi, ulihisi nini?"),
    ("migration", "Lugha mpya", "Kujifunza lugha mpya kulikuwaje — kilichokuwa vigumu zaidi ni nini?"),
    ("migration", "Sherehe mbali", "Uliisherehekea vipi sherehe muhimu ukiwa mbali na nyumbani?"),
    ("migration", "Kurudi nyumbani", "Tuambie kuhusu mara ya kwanza kurudi nyumbani — nani alikusubiri uwanjani wa ndege?"),
    ("migration", "Kwa ajili ya watoto", "Ni hadithi gani nyuma ya kuhamia kwa ajili ya elimu ya watoto?"),
    ("migration", "Kutafuta kazi", "Tuambie kuhusu mapambano ya kupata kazi mahali mapya."),
    ("migration", "Nyumba mbili", "Ni vipi kuwa na moyo uliogawanywa kati ya nchi mbili?"),
    ("migration", "Hati na viza", "Unakumbuka nini kuhusu mchakato wa viza au hati?"),
    ("migration", "Ladha ya nyumbani", "Ulipata lini wakati ulichokosa zaidi chakula cha mama au bibi?"),
    ("migration", "Umbali na familia", "Tuambie kuhusu usiku au siku ngumu zaidi mbali na familia."),
    ("migration", "Utambulisho mpya", "Ulijijenga vipi na kuunda maisha yako mahali mapya?"),
    ("migration", "Ndoto ya kurudi", "Unaota kurudi nyumbani — nini kinakuzuia au kinakuwezesha?"),
    ("legacy", "Ninachotaka kuacha", "Unataka kuwaachia watoto au wajukuu wako nini zaidi ya pesa?"),
    ("legacy", "Hadithi ya jina", "Je, kuna hadithi nyuma ya jina lako unayotaka kusimulia?"),
    ("legacy", "Asili ya familia", "Tuambie familia yako ilitoka wapi na ilifika hapa vipi."),
    ("legacy", "Somo la milele", "Unataka kizazi kijacho kisisahau nini kamwe?"),
    ("legacy", "Jinsi nikumbukwe", "Unataka ukumbukweje?"),
    ("legacy", "Picha yenye hadithi", "Ni hadithi gani iliyofichwa katika picha ya zamani inayopaswa kusimuliwa?"),
    ("legacy", "Urithi wa bibi", "Ni kitu gani au hekima kutoka kwa bibi unayotaka kuipitisha mbele?"),
    ("legacy", "Kijiji cha zamani", "Tuambie kuhusu kijiji au nyumba ambapo familia yako ilikulia."),
    ("legacy", "Kuwa pamoja", "Unatoa ushauri gani ili familia ibaki pamoja?"),
    ("legacy", "Mapambano yangu", "Ni sehemu gani ya mapambano yako unayotaka watoto wako waijue?"),
    ("legacy", "Wakati wa furaha", "Ni wakati gani wa maisha yako unayotaka uishi milele?"),
    ("legacy", "Msamaha au shukrani", "Unataka kumuomba msamaha au kumshukuru nani — na kwa nini?"),
    ("legacy", "Ndoto isiyokamilika", "Je, kuna ndoto yako unayotaka kizazi kijacho kitimize?"),
    ("legacy", "Desturi hai", "Ni desturi gani muhimu zaidi kuendeleza?"),
    ("legacy", "Ujumbe wangu wa mwisho", "Unataka kuwaacha na ujumbe gani wale unaowapenda zaidi?"),
]
