# Turkish questions — büyükanne, çay, Ramazan, köy/şehir, migration, traditions
TR = [
    ("childhood", "Büyükannenin kucağı", "Büyükannenin veya büyükbabanın kucağındaki en sıcak anınızı anlatır mısınız?"),
    ("childhood", "Gizli köşe", "Çocukken en sevdiğiniz gizli saklanma yeriniz neresiydi?"),
    ("childhood", "İlk okul günü", "İlk okul gününüz nasıldı — elinizi kim tuttu?"),
    ("childhood", "Mahallemiz", "Mahallenizden en sıcak hatıranız nedir — o dükkân, o ağaç, o sesler?"),
    ("childhood", "Yaz öğle uykusu", "Yaz öğle uykularında fanın altında ne hayal ederdiniz?"),
    ("childhood", "İlk bisiklet", "İlk bisikletinizi kim verdi ve o gün ne oldu?"),
    ("childhood", "Yağmurda oynamak", "Yağmurda oynamanın en eğlenceli anısını anlatır mısınız?"),
    ("childhood", "Büyükanne masalları", "Büyükannenizin hangi masalı hâlâ kalbinizde yaşıyor?"),
    ("childhood", "Kalabalık ev", "Kalabalık bir ailede yaşamanın en güzel anı hangisiydi?"),
    ("childhood", "Annenin ninnisi", "Annenizin hangi ninni veya şarkısı sizi hâlâ sakinleştiriyor?"),
    ("childhood", "Bayram hazırlığı", "Çocukken bayram hazırlıklarında ne yapardınız?"),
    ("childhood", "Babayla yürüyüş", "Babanızla okula veya pazara giderken neler konuşurdunuz?"),
    ("childhood", "Tatil günü", "Okul olmayan günlerde ne yapardınız — oyun, televizyon, başka?"),
    ("childhood", "Komşu teyze", "Mahalledeki bir teyze veya hala size ne öğretti ki unutamadınız?"),
    ("childhood", "İlk hediye", "Çocukluğunuzdaki o hediyeyi anlatın — kim verdi, nasıl hissettiniz?"),
    ("childhood", "Köy yazları", "Büyükanne köyünde veya yazlıkta geçen tatilleri hatırlıyor musunuz?"),
    ("childhood", "Sokak oyunları", "En sevdiğiniz sokak oyunu neydi ve kiminle oynardınız?"),
    ("childhood", "İlk param", "İlk kez kendi paranızı kazandığınız anı anlatır mısınız?"),
    ("childhood", "Çocukluk korkusu", "Hangi çocukluk korkusunu hatırlıyorsunuz ve kim yardım etti?"),
    ("childhood", "Kış masalı", "Çocukluğunuzun en büyülü kış gününü anlatır mısınız?"),
    ("family", "Babanın öğüdü", "Babanız size hayatın en önemli dersini ne öğretti?"),
    ("family", "Annenin mutfağı", "Annenizin hangi yemeği hâlâ dünyanın en güzeli?"),
    ("family", "Kardeşler", "Kardeşlerinizle en sıcak veya en komik anınızı anlatır mısınız?"),
    ("family", "Amca veya dayı", "Bir amca, dayı veya teyzenin hangi nasihatı bugün hâlâ size yol gösteriyor?"),
    ("family", "Aile sofrası", "Aile sofrasında unutulmaz bir akşamı anlatır mısınız?"),
    ("family", "Dedemin sesi", "Büyükbabanız nasıl konuşurdu — hangi sözü hâlâ kulaklarınızda?"),
    ("family", "Bir düğün", "Ailenizdeki bir düğün veya kutlamanın en değerli anısı nedir?"),
    ("family", "Hastalıkta birlik", "Biri hasta olduğunda aile nasıl bir araya geldi?"),
    ("family", "Eski fotoğraf", "En eski aile fotoğrafı size ne anlatıyor?"),
    ("family", "Büyükanne evi", "Büyükanne evini özel kılan neydi — kokular, sesler, atmosfer?"),
    ("family", "Nasıl tanıştık", "Eşinizle tanışma hikâyenizi anlatır mısınız?"),
    ("family", "Çocukların kahkahası", "Çocuklarınızla hangi an ruhunuza dokundu?"),
    ("family", "Bir barışma", "Aileyi güçlendiren bir anlaşmazlığı anlatır mısınız?"),
    ("family", "Büyükanne mutfağı", "Büyükanne mutfağının hangi kokusu sizi geçmişe götürüyor?"),
    ("family", "Kalabalık aile", "Kalabalık ve gürültülü bir ailede yaşamaktan ne öğrendiniz?"),
    ("family", "Evdeki ilahi", "Evinizde her sabah veya akşam hangi ilahi veya şarkı çalardı?"),
    ("family", "Büyüklerin duası", "Bir büyüğün duasını veya kucaklamasını hiç unutmadığınız anı anlatın."),
    ("family", "Aile gezisi", "Bir aile gezisini hatırlıyor musunuz — nereye gittiniz, ne oldu?"),
    ("family", "Sevilen akraba", "Her görüşmede sıcak hissettiren o akraba kimdi?"),
    ("family", "Bizim gücümüz", "Hangi anda ailenizin yenilmez olduğunu hissettiniz?"),
    ("lessons", "Hayat dersi", "Hayat size en zor ama en gerekli dersi ne öğretti?"),
    ("lessons", "Babanın sözü", "Babanız ne dedi ki o zaman anlamadınız ama şimdi anlıyorsunuz?"),
    ("lessons", "Başarısızlıktan", "Sizi ayağa kaldırmayı öğreten bir başarısızlığı anlatır mısınız?"),
    ("lessons", "Dürüstlük", "Evde doğruluk ve dürüstlük hakkında ne öğretildi?"),
    ("lessons", "Emeğin karşılığı", "Emekli çalışmanın değerini ilk ne zaman hissettiniz?"),
    ("lessons", "Sabır", "Sabretmeyi kimden öğrendiniz?"),
    ("lessons", "Okumanın değeri", "Sizi okumaya kim ve nasıl teşvik etti?"),
    ("lessons", "Hatadan", "Bir daha yapmadığınız hatayı ve ondan ne öğrendiğinizi anlatın."),
    ("lessons", "Başkalarına yardım", "Birine yardım etmek size ne öğretti?"),
    ("lessons", "Zaman", "Zamanın ne kadar değerli olduğunu ne zaman anladınız?"),
    ("lessons", "Alçakgönüllülük", "Alçakgönüllü olmayı nereden öğrendiniz?"),
    ("lessons", "Aile önce", "Ailenin her şeyden önce geldiğini hangi deneyim öğretti?"),
    ("lessons", "Kendine güven", "Kendinize güvenmeyi ne zaman ve nasıl öğrendiniz?"),
    ("lessons", "Affetmek", "Affetmeyi öğrendiğiniz bir anı anlatır mısınız?"),
    ("lessons", "Doğruyu söylemek", "Doğruyu söyleme cesaretini kim verdi?"),
    ("traditions", "Ramazan iftarı", "Ramazan iftar sofrasının en sıcak anısını anlatır mısınız?"),
    ("traditions", "Bayram sabahı", "Bayram sabahı evde neler olur — kıyafetler, ziyaretler, tatlılar?"),
    ("traditions", "Çay saati", "Aile çay saati nasıl geçerdi — kim demler, ne konuşulurdu?"),
    ("traditions", "İnanç geleneği", "Ailenizde hâlâ süren bir inanç veya dua geleneği var mı?"),
    ("traditions", "Kına gecesi", "Kına gecesi, sünnet düğünü veya başka bir kutlamayı anlatır mısınız?"),
    ("traditions", "Düğün töreni", "Hangi düğün töreni size en güzel geliyor ve neden?"),
    ("traditions", "Anma günü", "Aileniz vefat edenleri nasıl anıyor?"),
    ("traditions", "Doğum günü", "Kuşaktan kuşağa süren bir doğum günü geleneğiniz var mı?"),
    ("traditions", "Kurban Bayramı", "Kurban Bayramı veya başka bir dini bayramı anlatır mısınız?"),
    ("traditions", "Yeni yıl", "Aileniz yeni yılı nasıl karşılıyor — hangi ritüeller var?"),
    ("traditions", "Gizli tarif", "Hangi aile tarifi sadece özel günlerde yapılır?"),
    ("traditions", "Büyükanne deyişi", "Büyükannenizin hangi deyişini bugün hâlâ tekrarlarsınız?"),
    ("traditions", "Köy şenliği", "Köy veya mahalle şenliğinin en güzel anısını anlatır mısınız?"),
    ("traditions", "Kış geleneği", "Kışa özgü bir aile geleneğinizi anlatır mısınız?"),
    ("traditions", "Aktarmak istediğim", "Hangi aile geleneğini yaşatmak istiyorsunuz?"),
    ("migration", "Göç kararı", "Yurt dışına veya şehre göç kararı nasıl alındı — kim önerdi, ne hissettiniz?"),
    ("migration", "İlk gün", "Yeni ülkede veya şehirde ilk gününüz nasıldı — ne özlediniz?"),
    ("migration", "Hasret", "Uzakta en çok hangi ev anısı sizi vuruyor?"),
    ("migration", "Para göndermek", "Aileye para göndermeyi anlatır mısınız — neden, nasıl, ne hissettiniz?"),
    ("migration", "Yeni dil", "Yeni bir dil öğrenmek nasıldı — en zor neydi?"),
    ("migration", "Bayram uzakta", "Uzakta bir bayramı nasıl geçirdiniz?"),
    ("migration", "Dönüş", "İlk kez eve döndüğünüzde ne oldu — havaalanında kim vardı?"),
    ("migration", "Çocuklar için", "Çocukların eğitimi için taşınmanın hikâyesi nedir?"),
    ("migration", "İş aramak", "Yeni yerde iş bulma mücadelenizi anlatır mısınız?"),
    ("migration", "İki ev", "Kalbin iki ülke veya iki şehir arasında bölünmüş olması nasıl hissettiriyor?"),
    ("migration", "Vize süreci", "Vize veya evrak işlemlerinden ne hatırlıyorsunuz?"),
    ("migration", "Ev yemeği", "Annenizin veya büyükannenizin yemeğini en çok ne zaman özlediniz?"),
    ("migration", "Aileden uzak", "Aileden uzakta en zor gece veya günü anlatır mısınız?"),
    ("migration", "Yeni kimlik", "Yeni yerde kendinizi ve hayatınızı nasıl kurdunuz?"),
    ("migration", "Dönme hayali", "Eve dönmeyi hayal ediyor musunuz — ne engelliyor veya ne mümkün kılıyor?"),
    ("legacy", "Bırakmak istediğim", "Çocuklarınıza veya torunlarınıza paradan başka ne bırakmak istiyorsunuz?"),
    ("legacy", "Soyadı hikâyesi", "Soyadınızın arkasında anlatılması gereken bir hikâye var mı?"),
    ("legacy", "Ailemizin kökeni", "Ailenizin nereden geldiğini ve buraya nasıl yerleştiğini anlatır mısınız?"),
    ("legacy", "Sonsuza dek ders", "Gelecek neslin asla unutmamasını istediğiniz şey nedir?"),
    ("legacy", "Nasıl hatırlansın", "İnsanlar sizi nasıl hatırlasın istiyorsunuz?"),
    ("legacy", "Fotoğraftaki hikâye", "Anlatılması gereken eski bir fotoğrafta hangi hikâye gizli?"),
    ("legacy", "Büyükanne mirası", "Büyükannenizden veya büyükbabanızdan aktarmak istediğiniz şey nedir?"),
    ("legacy", "Köy evi", "Ailenizin büyüdüğü köy veya evi anlatır mısınız?"),
    ("legacy", "Bir arada kalmak", "Aileyi bir arada tutmak için ne tavsiye verirsiniz?"),
    ("legacy", "Mücadelem", "Çocuklarınızın bilmesini istediğiniz mücadelenizin hangi kısmı?"),
    ("legacy", "Mutlu an", "Hayatınızın hangi anının sonsuza dek yaşamasını istiyorsunuz?"),
    ("legacy", "Özür veya teşekkür", "Kime özür dilemek veya teşekkür etmek istiyorsunuz — neden?"),
    ("legacy", "Tamamlanmamış rüya", "Gelecek neslin gerçekleştirmesini istediğiniz bir rüyanız var mı?"),
    ("legacy", "Yaşayan gelenek", "Hangi geleneği yaşatmak en önemli?"),
    ("legacy", "Son sözüm", "En sevdiklerinize ne söylemek istiyorsunuz?"),
]
