/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecapRouteImport } from './routes/recap'
import { Route as QuickQuestionRouteImport } from './routes/quick-question'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ModeRouteImport } from './routes/mode'
import { Route as MatchRouteImport } from './routes/match'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as LoungeRouteImport } from './routes/lounge'
import { Route as GratitudeRouteImport } from './routes/gratitude'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const RecapRoute = RecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickQuestionRoute = QuickQuestionRouteImport.update({
  id: '/quick-question',
  path: '/quick-question',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeRoute = ModeRouteImport.update({
  id: '/mode',
  path: '/mode',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoungeRoute = LoungeRouteImport.update({
  id: '/lounge',
  path: '/lounge',
  getParentRoute: () => rootRouteImport,
} as any)
const GratitudeRoute = GratitudeRouteImport.update({
  id: '/gratitude',
  path: '/gratitude',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkin': typeof CheckinRoute
  '/gratitude': typeof GratitudeRoute
  '/lounge': typeof LoungeRoute
  '/manifesto': typeof ManifestoRoute
  '/match': typeof MatchRoute
  '/mode': typeof ModeRoute
  '/onboarding': typeof OnboardingRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/quick-question': typeof QuickQuestionRoute
  '/recap': typeof RecapRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkin': typeof CheckinRoute
  '/gratitude': typeof GratitudeRoute
  '/lounge': typeof LoungeRoute
  '/manifesto': typeof ManifestoRoute
  '/match': typeof MatchRoute
  '/mode': typeof ModeRoute
  '/onboarding': typeof OnboardingRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/quick-question': typeof QuickQuestionRoute
  '/recap': typeof RecapRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkin': typeof CheckinRoute
  '/gratitude': typeof GratitudeRoute
  '/lounge': typeof LoungeRoute
  '/manifesto': typeof ManifestoRoute
  '/match': typeof MatchRoute
  '/mode': typeof ModeRoute
  '/onboarding': typeof OnboardingRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/quick-question': typeof QuickQuestionRoute
  '/recap': typeof RecapRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkin'
    | '/gratitude'
    | '/lounge'
    | '/manifesto'
    | '/match'
    | '/mode'
    | '/onboarding'
    | '/profile-setup'
    | '/quick-question'
    | '/recap'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkin'
    | '/gratitude'
    | '/lounge'
    | '/manifesto'
    | '/match'
    | '/mode'
    | '/onboarding'
    | '/profile-setup'
    | '/quick-question'
    | '/recap'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkin'
    | '/gratitude'
    | '/lounge'
    | '/manifesto'
    | '/match'
    | '/mode'
    | '/onboarding'
    | '/profile-setup'
    | '/quick-question'
    | '/recap'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckinRoute: typeof CheckinRoute
  GratitudeRoute: typeof GratitudeRoute
  LoungeRoute: typeof LoungeRoute
  ManifestoRoute: typeof ManifestoRoute
  MatchRoute: typeof MatchRoute
  ModeRoute: typeof ModeRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  QuickQuestionRoute: typeof QuickQuestionRoute
  RecapRoute: typeof RecapRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recap': {
      id: '/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof RecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-question': {
      id: '/quick-question'
      path: '/quick-question'
      fullPath: '/quick-question'
      preLoaderRoute: typeof QuickQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mode': {
      id: '/mode'
      path: '/mode'
      fullPath: '/mode'
      preLoaderRoute: typeof ModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lounge': {
      id: '/lounge'
      path: '/lounge'
      fullPath: '/lounge'
      preLoaderRoute: typeof LoungeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gratitude': {
      id: '/gratitude'
      path: '/gratitude'
      fullPath: '/gratitude'
      preLoaderRoute: typeof GratitudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckinRoute: CheckinRoute,
  GratitudeRoute: GratitudeRoute,
  LoungeRoute: LoungeRoute,
  ManifestoRoute: ManifestoRoute,
  MatchRoute: MatchRoute,
  ModeRoute: ModeRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  QuickQuestionRoute: QuickQuestionRoute,
  RecapRoute: RecapRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
