// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rynnnhxfrcebdandsbjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5bm5uaHhmcmNlYmRhbmRzYmpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxOTgwODEsImV4cCI6MjA5MDc3NDA4MX0.l58jEH3s6ZBDILqU9qMXM4AzahxNvo4tlfCTiuddZ70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});